# Generated by Django 5.2.7 on 2026-02-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprendizado', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.assunto')),
            ],
            options={
                'verbose_name_plural': 'aprendizados',
            },
        ),
    ]
